package entity;
// default package

import java.util.Date;


/**
 * User generated by MyEclipse Persistence Tools
 */

public class User  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String username;
     private String password;
     private String name;
     private String phone;
     private Date registDate;


    // Constructors

    /** default constructor */
    public User() {
    }

    
    /** full constructor */
    public User(String username, String password, String name, String phone, Date registDate) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.phone = phone;
        this.registDate = registDate;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Date getRegistDate() {
        return this.registDate;
    }
    
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }
   








}